package midproject.Client;

import com.toedter.calendar.JDateChooser;
import midproject.Functions;
import midproject.Interfaces.EntryInterface;
import midproject.Serializables.Employee;
import midproject.Server.ServerWindow;
import midproject.TextAreaOutputStream;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.PrintStream;
import java.rmi.RemoteException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.util.*;

public class ManageAccountWindow extends javax.swing.JFrame {
    // Variables declaration - do not modify
    private javax.swing.JLabel jBirthDateLabel;
    private com.toedter.calendar.JDateChooser jBirthdayChooser;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JButton jConfirmButton;
    private javax.swing.JButton jNewAccountButton;
    private javax.swing.JTextField jEmailAddressField;
    private javax.swing.JLabel jEmailAddressLabel;
    private javax.swing.JTextField jFirstNameField;
    private javax.swing.JLabel jFirstNameLabel;
    private javax.swing.JComboBox<String> jGenderBox;
    private javax.swing.JLabel jGenderLabel;
    private javax.swing.JComboBox<String> jIDNumberBox;
    private javax.swing.JLabel jIDNumberLabel;
    private javax.swing.JLabel jPostionLabel;
    private javax.swing.JTextField jLastNameField;
    private javax.swing.JLabel jLastNameLabel;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JTextField jMiddleNameField;
    private javax.swing.JLabel jMiddleNameLabel;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel jPasswordLabel;
    private javax.swing.JTextField jPositionField;
    private javax.swing.JLabel jVerifyPWLabel;
    private java.awt.Checkbox check;
    private final Image icon = Toolkit.getDefaultToolkit().getImage("res\\img\\croppedLogo.png");

    Employee employee;

    Employee selectedEmployee;
    Employee verifyEmployee;
    Employee updatedSelectedEmployee;

    EntryInterface entryInterface;
    SummaryWindow summaryWindow;
    // END OF Declaration

    /**
     * Creates new form ManageAccountWindow
     */
    public ManageAccountWindow(Employee employee, EntryInterface entryInterface, SummaryWindow summaryWindow) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            this.employee = employee;
            this.entryInterface = entryInterface;
            this.summaryWindow = summaryWindow;

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAccountWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jMainPanel = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics graphics) {
                super.paintComponent(graphics);
                Graphics2D graphics2D = (Graphics2D) graphics;
                graphics2D.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
                int width = getWidth();
                int height = getHeight();
                Color color1 = new java.awt.Color(83, 193, 246);
                Color color2 = new java.awt.Color(32, 153, 136);
                GradientPaint gradientPaint = new GradientPaint(0, 0, color1, 0, height, color2);
                graphics2D.setPaint(gradientPaint);
                graphics2D.fillRect(0, 0, width, height);
            }
        };

        jIDNumberLabel = new javax.swing.JLabel();
        jLastNameLabel = new javax.swing.JLabel();
        jFirstNameLabel = new javax.swing.JLabel();
        jMiddleNameLabel = new javax.swing.JLabel();
        jLastNameField = new javax.swing.JTextField();
        jFirstNameField = new javax.swing.JTextField();
        jMiddleNameField = new javax.swing.JTextField();
        jIDNumberBox = new javax.swing.JComboBox<>();
        jBirthdayChooser = new com.toedter.calendar.JDateChooser();
        jBirthDateLabel = new javax.swing.JLabel();
        jPostionLabel = new javax.swing.JLabel();
        jPositionField = new javax.swing.JTextField();
        jGenderBox = new javax.swing.JComboBox<>();
        jGenderLabel = new javax.swing.JLabel();
        jEmailAddressLabel = new javax.swing.JLabel();
        jEmailAddressField = new javax.swing.JTextField();
        jPasswordLabel = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jVerifyPWLabel = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jConfirmButton = new javax.swing.JButton();
        jCancelButton = new javax.swing.JButton();
        jNewAccountButton = new javax.swing.JButton();
        check = new java.awt.Checkbox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        //Set Labels
        setLabels(jIDNumberLabel, jLastNameLabel, jFirstNameLabel, jMiddleNameLabel, jBirthDateLabel,
                  jPostionLabel, jGenderLabel, jEmailAddressLabel, jPasswordLabel, jVerifyPWLabel);
        //Set TextBoxes
        setMiscellaneous(jLastNameField, jFirstNameField, jMiddleNameField, jEmailAddressField,
                jIDNumberBox, jBirthdayChooser, jPositionField,  jGenderBox,
                jPasswordField , jPasswordField1, check);
        setjCancelButton(jCancelButton);
        setjConfirmButton(jConfirmButton);
        setjNewAccountButton(jNewAccountButton);
        setjIDNumberBox(jIDNumberBox);
        setMainFrameListener(this);
        setCheck(check);
        jIDNumberBox.addActionListener(this::jIDNumberBoxActionPerformed);

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
                jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jMainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jMainPanelLayout.createSequentialGroup()
                                                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jMainPanelLayout.createSequentialGroup()
                                                                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jBirthDateLabel)
                                                                        .addComponent(jGenderLabel)
                                                                        .addComponent(jEmailAddressLabel))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jBirthdayChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jGenderBox, 0, 189, Short.MAX_VALUE)
                                                                        .addComponent(jEmailAddressField)))
                                                        .addGroup(jMainPanelLayout.createSequentialGroup()
                                                                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLastNameLabel)
                                                                        .addComponent(jMiddleNameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jFirstNameLabel))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jFirstNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                                                        .addComponent(jLastNameField)
                                                                        .addComponent(jMiddleNameField, javax.swing.GroupLayout.Alignment.TRAILING))))
                                                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jMainPanelLayout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jIDNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jPostionLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                        .addGroup(jMainPanelLayout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jVerifyPWLabel)
                                                                        .addComponent(jPasswordLabel))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGroup(jMainPanelLayout.createSequentialGroup()
                                                .addComponent(jCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(92, 92, 92)
                                                .addComponent(jNewAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jConfirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                        .addComponent(jPasswordField)
                                        .addComponent(jPositionField)
                                        .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jIDNumberBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())
        );

        jMainPanelLayout.setVerticalGroup(
                jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jMainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jIDNumberLabel)
                                        .addComponent(jLastNameLabel)
                                        .addComponent(jLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jIDNumberBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jFirstNameLabel)
                                        .addComponent(jFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPostionLabel)
                                        .addComponent(jPositionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jMiddleNameLabel)
                                        .addComponent(jMiddleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jBirthdayChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jBirthDateLabel))
                                        .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jPasswordLabel)
                                                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jGenderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jGenderLabel)
                                        .addComponent(jVerifyPWLabel)
                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jMainPanelLayout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jEmailAddressLabel)
                                                        .addComponent(jEmailAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jMainPanelLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jNewAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        setIconImage(icon);
        setResizable(false);
        pack();
    }// </editor-fold>

    private void setLabels(JLabel jIDNumberLabel, JLabel jLastNameLabel, JLabel jFirstNameLabel, JLabel jMiddleNameLabel, JLabel jBirthDateLabel,
                           JLabel jPostionLabel, JLabel jGenderLabel, JLabel jEmailAddressLabel, JLabel jPasswordLabel, JLabel jVerifyPWLabel){

        ArrayList<JLabel> jLabelArrayList = new ArrayList<>();
        jLabelArrayList.add(jLastNameLabel); jLabelArrayList.add(jFirstNameLabel); jLabelArrayList.add(jMiddleNameLabel);
        jLabelArrayList.add(jIDNumberLabel); jLabelArrayList.add(jGenderLabel); jLabelArrayList.add(jEmailAddressLabel);
        jLabelArrayList.add(jPasswordLabel); jLabelArrayList.add(jVerifyPWLabel); jLabelArrayList.add(jBirthDateLabel);
        jLabelArrayList.add(jPostionLabel);

        for(JLabel JLabel : jLabelArrayList){
            JLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        }

        jIDNumberLabel.setText("ID Number :");
        jLastNameLabel.setText("Last Name :");
        jFirstNameLabel.setText("First Name :");
        jMiddleNameLabel.setText("Middle Name :");
        jBirthDateLabel.setText("Birth Date :");
        jPostionLabel.setText("Position :");
        jGenderLabel.setText("Gender :");
        jEmailAddressLabel.setText("E-mail :");
        jPasswordLabel.setText("Password :");
        jVerifyPWLabel.setText("Verify PW :");
    }

    private void setMiscellaneous(JTextField jLastNameField, JTextField jFirstNameField, JTextField jMiddleNameField, JTextField jEmailAddressField,
                                  JComboBox<String> jIDNumberBox, JDateChooser jBirthdayChooser, JTextField jPositionField, JComboBox<String> jGenderBox,
                                  JPasswordField jPasswordField , JPasswordField jPasswordField1, Checkbox jViewCheckBox){

        ArrayList<JTextField> jLabelArrayList = new ArrayList<>();
        jLabelArrayList.add(jLastNameField); jLabelArrayList.add(jFirstNameField); jLabelArrayList.add(jMiddleNameField);
        jLabelArrayList.add(jEmailAddressField); jLabelArrayList.add(jPositionField); jLabelArrayList.add(jPasswordField);
        jLabelArrayList.add(jPasswordField1);

        for(JTextField JTextField : jLabelArrayList){
            JTextField.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        }

        jIDNumberBox.setFont(new java.awt.Font("Arial", 0, 13));
        jBirthdayChooser.setDateFormatString("yyyy-MM-dd");
        jBirthdayChooser.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jGenderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Select one", "Male", "Female"}));
        jViewCheckBox.setLabel("Show Password");

        disableTextBoxes();
    }

    public void setjIDNumberBox(JComboBox<String> jIDNumberBox) {
        jIDNumberBox.addItem("Select Employee");

        try{
            for(Integer key : entryInterface.getEmployeeHashMap().keySet()){
                jIDNumberBox.addItem(key.toString());
            }
        }catch (RemoteException e) {
            e.printStackTrace();
        }
    }

    private void jIDNumberBoxActionPerformed(ActionEvent evt){
        String selectedIDNumber = Objects.requireNonNull(jIDNumberBox.getSelectedItem()).toString();

        try {
            if(!selectedIDNumber.equals("Select Employee")){
                enableTextBoxes();
                selectedEmployee = entryInterface.getEmployeeData(Integer.parseInt(selectedIDNumber));

                jLastNameField.setText(selectedEmployee.getLastName());
                jFirstNameField.setText(selectedEmployee.getFirstName());
                jMiddleNameField.setText(selectedEmployee.getMiddleName());

                SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
                Date date = simpleDateFormat.parse(selectedEmployee.getBirthdate());

                jPositionField.setText(selectedEmployee.getPosition());
                jGenderBox.setSelectedItem(selectedEmployee.getGender());

                jBirthdayChooser.setDate(date);
                jPasswordField.setText(selectedEmployee.getPassword());
                jPasswordField1.setText(selectedEmployee.getPassword());
                jEmailAddressField.setText(selectedEmployee.getEmailAddress());

            }
            else{
                disableTextBoxes();
                clearTextBoxes();
            }
        }catch (RemoteException | ParseException e) {
            e.printStackTrace();
        }
    }

    private void setCheck(Checkbox check){
        check.addItemListener(e -> {
            if(e.getStateChange() == ItemEvent.SELECTED){
                jPasswordField.setEchoChar((char) 0);
                jPasswordField1.setEchoChar((char) 0);
            }
            else{
                jPasswordField.setEchoChar('*');
                jPasswordField1.setEchoChar('*');
            }
        });
    }

    private void setjConfirmButton(JButton jConfirmButton) {
        jConfirmButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jConfirmButton.setText("Confirm");

        jConfirmButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jConfirmButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                super.mouseEntered(e);
                jConfirmButton.setBackground(new java.awt.Color(0, 204, 204));
                jConfirmButton.setForeground(new java.awt.Color(0, 0, 0));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                super.mouseExited(e);
                jConfirmButton.setBackground(new java.awt.Color(204, 204, 204));
                jConfirmButton.setForeground(new java.awt.Color(0, 0, 0));
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                confirmButtonInitiate();
            }
        });
    }

    private void setjCancelButton(JButton jCancelButton) {
        jCancelButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jCancelButton.setText("Cancel");

        jCancelButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCancelButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                super.mouseEntered(e);
                jCancelButton.setBackground(new java.awt.Color(0, 204, 204));
                jCancelButton.setForeground(new java.awt.Color(0, 0, 0));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                super.mouseExited(e);
                jCancelButton.setBackground(new java.awt.Color(204, 204, 204));
                jCancelButton.setForeground(new java.awt.Color(0, 0, 0));
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                setVisible(false);
                dispose();
                summaryWindow.setVisible(true);
            }
        });
    }

    public void setjNewAccountButton(JButton jNewAccountButton) {
        jNewAccountButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jNewAccountButton.setText("New Account");

        jNewAccountButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jNewAccountButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                super.mouseEntered(e);
                jNewAccountButton.setBackground(new java.awt.Color(0, 204, 204));
                jNewAccountButton.setForeground(new java.awt.Color(0, 0, 0));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                super.mouseExited(e);
                jNewAccountButton.setBackground(new java.awt.Color(204, 204, 204));
                jNewAccountButton.setForeground(new java.awt.Color(0, 0, 0));
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                RegisterWindow();
            }
        });
    }

    private void confirmButtonInitiate(){
        try{

            char[] passwordChar = jPasswordField.getPassword();
            char[] verifyPasswordChar = jPasswordField1.getPassword();

            int idNumber = selectedEmployee.getID_Number();
            String Password = new String(passwordChar);
            String verifyPassword = new String(verifyPasswordChar);

            String lastName = jLastNameField.getText();
            String firstName = jFirstNameField.getText();
            String middleName = jMiddleNameField.getText();

            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String newBirthdate = simpleDateFormat.format(jBirthdayChooser.getDate());

            String position = jPositionField.getText();
            String email = jEmailAddressField.getText();
            String gender = (String) jGenderBox.getSelectedItem();
            int age = Functions.calculateAge(newBirthdate);

            verifyEmployee = new Employee(idNumber, Password, lastName, firstName, middleName, newBirthdate, position, email, age, gender);

            if(selectedEmployee.EmployeeInformation_toString().equals(verifyEmployee.EmployeeInformation_toString())){
                JOptionPane.showMessageDialog(null, "There were no changes made.", "No changes were detected!", JOptionPane.WARNING_MESSAGE);
            }
            else{
                if(Password.equals(verifyPassword)){

                    int choice = JOptionPane.showConfirmDialog(null, "Data of ID Number: " + verifyEmployee.getID_Number() + " will be updated, continue?", "Verify.", JOptionPane.YES_NO_OPTION);

                    if (choice == 0){
                        updatedSelectedEmployee = verifyEmployee;

                        entryInterface.updateEmployee(updatedSelectedEmployee);
                        entryInterface.UpdateToLogs(employee, selectedEmployee);
                        JOptionPane.showMessageDialog(null, "Employee Number: " + updatedSelectedEmployee.getID_Number() + " details has been updated.", "Updated Employee Successfully!", JOptionPane.INFORMATION_MESSAGE);
                        jIDNumberBox.addActionListener(this::jIDNumberBoxActionPerformed);
                    }

                }
                else{
                    JOptionPane.showMessageDialog(null, "Please recheck your passwords.", "Password(s) do not match!", JOptionPane.WARNING_MESSAGE);
                }
            }

        }catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void setMainFrameListener(JFrame MainFrame){
        MainFrame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                summaryWindow.setVisible(true);
                super.windowClosing(e);
            }
            @Override
            public void windowClosed(WindowEvent e) {
                summaryWindow.setVisible(true);
                super.windowClosed(e);
            }
        });
    }

    private void clearTextBoxes(){
        jIDNumberBox.setSelectedItem("Select Employee");
        jLastNameField.setText("");
        jFirstNameField.setText("");
        jMiddleNameField.setText("");
        jPositionField.setText("");
        jGenderBox.setSelectedItem("");
        jPasswordField.setText("");
        jPasswordField1.setText("");
        jEmailAddressField.setText("");
    }

    private void disableTextBoxes(){

        ArrayList<JTextField> jLabelArrayList = new ArrayList<>();
        jLabelArrayList.add(jLastNameField); jLabelArrayList.add(jFirstNameField); jLabelArrayList.add(jMiddleNameField);
        jLabelArrayList.add(jEmailAddressField); jLabelArrayList.add(jPositionField); jLabelArrayList.add(jPasswordField);
        jLabelArrayList.add(jPasswordField1);

        for(JTextField JTextField : jLabelArrayList){
            JTextField.setEnabled(false);
        }

        jBirthdayChooser.setEnabled(false);
        jGenderBox.setEnabled(false);
        check.setEnabled(false);
    }

    private void enableTextBoxes(){

        ArrayList<JTextField> jLabelArrayList = new ArrayList<>();
        jLabelArrayList.add(jLastNameField); jLabelArrayList.add(jFirstNameField); jLabelArrayList.add(jMiddleNameField);
        jLabelArrayList.add(jEmailAddressField); jLabelArrayList.add(jPositionField); jLabelArrayList.add(jPasswordField);
        jLabelArrayList.add(jPasswordField1);

        for(JTextField JTextField : jLabelArrayList){
            JTextField.setEnabled(true);
        }

        jBirthdayChooser.setEnabled(true);
        jGenderBox.setEnabled(true);
        check.setEnabled(true);

    }

    private void RegisterWindow(){
        RegisterWindow registerWindow = new RegisterWindow(employee, entryInterface, this);
        registerWindow.setVisible(true);
        registerWindow.setLocationRelativeTo(null);
        setVisible(false);
    }

}